# Generated by Django 5.0.7 on 2024-07-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_status_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='name',
            new_name='bike',
        ),
    ]
