# Generated by Django 5.0.7 on 2024-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_rename_name_bike_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
