# Generated by Django 5.0.7 on 2024-07-31 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_bike_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='is_available',
        ),
    ]
