# Generated by Django 5.0.7 on 2024-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_remove_bike_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
